### ISSUE TITLE
Icon of Default resource pack replaced with couplings icon

### ISSUE THREAD

**Issue by BBftw** [InsomniaKitten/Couplings#11]
![2020-01-21_14 46 40](https://user-images.githubusercontent.com/31790318/72773940-ec757580-3c5c-11ea-963a-10e3fa2f12b4.png)
Not sure if it's caused by optifine, but for some reason the couplings mod icon replaces the icon of the default texture pack

**Comment by ChloeDawn** [comment]
This is a problem with how Fabric's API handles resource packs.

**Comment by LemmaEOF** [comment]
It doesn't do this if you move it to `assets/pack.png` instead of just `pack.png`.

**Comment by ChloeDawn** [comment]
It is my resource/data pack icon, it is supposed to be where it is.
Fabric using it for an unrelated resource pack is not my mod's problem.

**Comment by LemmaEOF** [comment]
But it's *not* a resource/data pack icon, it's a *mod* icon. You don't *have* a visible resource/data pack for the icon to apply to; it's hidden in the resource pack view.

**Comment by ChloeDawn** [comment]
Mod jars are automatically loaded as resource/data packs. Just because they are not visible in the GUI does not mean they do not exist. If you queried my resource/data pack via the resource manager, you would be exposed to my resource/data pack icon.

The issue is on Fabric's end for using a file from an arbitrary jar for the vanilla resource pack icon. Vanilla does not have this issue with zip/folder resource packs, it is an issue exclusive to Fabric's resource loading. Mods shouldn't be expected to work around this bug.
